### ISSUE TITLE
Object published with inaccurate TF

### ISSUE THREAD

**Issue by khaledhazime** [robofeiathome/detector_2d#12]
An issue has been identified with the published TF of the object. It appears that the TF is being published slightly above the actual object, but the published coordinate seems to be in the correct "z" position. However, there is a significant error in the "x" position.

**Comment by MaSNogueiraS** [comment]
On line 126, there was an error in the coordinates of the transformation, as the y-axis was inverted. To fix the issue with the tf's being above the objects when they should actually be below, I simply removed the negative sign from the y-axis.
